# Δημιουργία του αρχείου docker/docker-compose.yml
services:
  node0:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node0
    command: ["-m", "cli.main", "--id", "node0", "--host", "0.0.0.0", "--port", "7000", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8000", "--debug"]
    ports:
      - "7100:7000"
      - "8100:8000"
    volumes:
      - raft_data:/app/data
    networks:
      raft_network:
        aliases:
          - node0
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Προσθήκη healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node1
    command: ["-m", "cli.main", "--id", "node1", "--host", "0.0.0.0", "--port", "7001", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8001", "--debug"]
    ports:
      - "7101:7001"
      - "8101:8001"
    volumes:
      - raft_data:/app/data
    networks:
      raft_network:
        aliases:
          - node1
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      node0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node2
    command: ["-m", "cli.main", "--id", "node2", "--host", "0.0.0.0", "--port", "7002", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8002", "--debug"]
    ports:
      - "7102:7002"
      - "8102:8002"
    volumes:
      - raft_data:/app/data
    networks:
      raft_network:
        aliases:
          - node2
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  raft_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  raft_data:
    driver: local