version: '3'

services:
  node0:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    command: ["-m", "cli.main", "--id", "node0", "--host", "0.0.0.0", "--port", "7000", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8000"]
    ports:
      - "7100:7000"  # Εξωτερική θύρα 7100, εσωτερική 7000
      - "8100:8000"  # Εξωτερική θύρα 8100, εσωτερική 8000
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network

  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    command: ["-m", "cli.main", "--id", "node1", "--host", "0.0.0.0", "--port", "7001", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8001"]
    ports:
      - "7101:7001"  # Εξωτερική θύρα 7101, εσωτερική 7001
      - "8101:8001"  # Εξωτερική θύρα 8101, εσωτερική 8001
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    command: ["-m", "cli.main", "--id", "node2", "--host", "0.0.0.0", "--port", "7002", "--cluster", "node0:7000,node1:7001,node2:7002", "--api-port", "8002"]
    ports:
      - "7102:7002"  # Εξωτερική θύρα 7102, εσωτερική 7002
      - "8102:8002"  # Εξωτερική θύρα 8102, εσωτερική 8002
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network

networks:
  raft_network:
    driver: bridge

volumes:
  raft_data: