version: '3.8'

services:
  node0:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node0
    # Χρήση σωστής διευθυνσιοδότησης για το cluster
    command: ["-m", "cli.main", "--id", "node0", "--host", "0.0.0.0", "--port", "7000", "--cluster", "raft-node0:7000,raft-node1:7001,raft-node2:7002", "--api-port", "8000", "--debug"]
    ports:
      - "7100:7000"
      - "8100:8000"
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node1
    command: ["-m", "cli.main", "--id", "node1", "--host", "0.0.0.0", "--port", "7001", "--cluster", "raft-node0:7000,raft-node1:7001,raft-node2:7002", "--api-port", "8001", "--debug"]
    ports:
      - "7101:7001"
      - "8101:8001"
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      node0:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: raft-node2
    command: ["-m", "cli.main", "--id", "node2", "--host", "0.0.0.0", "--port", "7002", "--cluster", "raft-node0:7000,raft-node1:7001,raft-node2:7002", "--api-port", "8002", "--debug"]
    ports:
      - "7102:7002"
      - "8102:8002"
    volumes:
      - raft_data:/app/data
    networks:
      - raft_network
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  raft_network:
    driver: bridge

volumes:
  raft_data:
    driver: local